name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
    - name: Install dependencies
      run: |
        sudo timedatectl set-timezone America/New_York
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade setuptools
        python3 -m pip install -r $GITHUB_WORKSPACE/requirements.txt
        python3 -m pip install pytest flake8 flaky pytest-xdist pytest-github-actions-annotate-failures
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - name: Actually annotate with flake8
      run: |           
        flake8 . --ignore=F821 --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics # treats errors as warnings
    - name: Test with pytest
      run: |
        cd $GITHUB_WORKSPACE/contracts/
        python3 -m pytest tests/* --force-flaky -v -n 2
    # - name: Upload to codecov
    #  uses: codecov/codecov-action@v1
    #  with:
    #    file: contracts/coverage.xml
    #    flags: unittests
    #    env_vars: OS, PYTHON
